# 5 nodes (2 control + 3 workers) cluster config
# For more info, please visit:
# https://kind.sigs.k8s.io
#
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
    - role: control-plane
    - role: control-plane
    - role: worker
    - role: worker
    - role: worker
